name: Java & React CI/CD with Docker

# 1. 워크플로우 실행 조건: dev 브랜치에 push가 발생했을 때
on:
  push:
    branches: [ "dev" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 이 작업은 GitHub가 제공하는 가상 서버에서 실행됨

    steps:
      # 2. 소스 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # 3. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. 백엔드/프론트엔드 이미지 빌드 및 Docker Hub에 푸시
      # Docker Compose의 build, push 명령어를 사용하면 여러 이미지를 쉽게 관리 가능
      - name: Build and push Docker images
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push
        # 참고: docker-compose.yml 파일에 image 이름을 명시해야 push가 동작합니다.
        # 예: image: suho1/having-backend:latest

      # 5. SSH로 OCI 서버에 접속하여 배포 스크립트 실행
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          script: |
            # 서버에서 실행될 스크립트
            cd ~/having  # 프로젝트 디렉토리로 이동
            echo "${{ secrets.ENV_FILE }}" > .env # GitHub Secret에서 .env 파일 생성
            
            # Docker Hub에서 최신 이미지 받아오기
            docker compose pull
            
            # 기존 컨테이너 내리고 최신 이미지로 다시 실행
            docker compose up -d
            
            # 불필요한 Docker 이미지 정리 (선택 사항)
            docker image prune -f